### ISSUE TITLE
yarn start error

### ISSUE THREAD

**Issue by kenneth** [Uniswap/uniswap-org#158]
```
 ERROR
      "bucketName" is a required option for gatsby-plugin-s3
      See docs here - https://github.com/jariz/gatsby-plugin-s3
not finished onPreBootstrap - 0.027s
error Command failed with exit code 1.
```

**Comment by callil** [comment]
For now you can just comment this out. Will update it to not be required for running `yarn dev`

**Comment by maurelian** [comment]
It's not jsut a requirement for `yarn dev`, it also seems to be required just to run `yarn start`. IMO it's important to keep the bar low for anyone to run the site locally ([ie](https://twitter.com/paddypisa/status/1305115156385497088?s=20)).

For others encountering this issue, the fix for me was:

1. open `gatsby-config.js`
2. comment out these lines: 
![image](https://user-images.githubusercontent.com/23033765/93483199-94b40a80-f8ce-11ea-9358-3e2b0949d62b.png)
3. now you should be able to build and serve it locally using `yarn start`.

**Comment by callil** [comment]
I agree - this was a recent change due to vercel hosting restrictions. Does anyone know how to have a set of gatsby plugins that only run on build or behind a flag? I was unable to find anything about this in the documentation.

**Comment by maurelian** [comment]
#170 is an option using env variables. I'm sure it could be tidied up a bit, but it gives an idea that you can run with.

**Comment by kenneth** [comment]
```
$ gatsby develop
success open and validate gatsby-configs - 0.278s
success load plugins - 2.943s
success onPreInit - 0.019s
success initialize cache - 0.041s
success copy gatsby files - 0.136s
success onPreBootstrap - 0.025s
success createSchemaCustomization - 0.008s
⠸ source and transform nodes
```

for a long time and i stop it

**Comment by molecula451** [comment]
I am able to reproduce this one. Commenting out  S3 plugin works to yarn locally.
